### ISSUE TITLE
command line options

### ISSUE THREAD

**Issue by gambol99** [UKHomeOffice/vaultconf#8]
- can we have vault address default to VAULT_ADDR
- the password masked and read from stdin

**Comment by timgent** [comment]
Yes we can. Currently you can configure your password in a ~/.vaultconf/login file in this format

``` yaml
---
username: myusername
password: mypassword
```

Would you like option to enter it from stdin as well as this?
